In [1]:
import os
os.chdir("..")
print(os.getcwd())

c:\Users\bradl\Documents\Projets Perso\real-estate-ai-agent

In [2]:
import polars as pl
from app.core.paths import BRONZE_DIR
import requests
import time
import re
import unicodedata

***


# DVF bronze cleaning

### 1. Import

In [25]:
dvf_df = pl.read_csv(BRONZE_DIR / "dvf.csv",
                     separator=",",
                     infer_schema_length=0
                     )

In [26]:
dvf_df.shape

(395612, 41)

In [22]:
dvf_df.head()

shape: (5, 1)
┌─────────────────────────────────┐
│ id_mutation,date_mutation,nume… │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ 2020-815165,2020-10-08,1,Vente… │
│ 2020-814507,2020-07-02,1,Vente… │
│ 2020-814508,2020-07-01,1,Vente… │
│ 2020-814509,2020-07-01,1,Vente… │
│ 2020-814509,2020-07-01,1,Vente… │
└─────────────────────────────────┘

In [13]:
# Remove duplicate header rows
dvf_df = dvf_df.remove(dvf_df["date_mutation"].str.contains("[a-zA-Z]"))

### 2. Typage des colonnes

In [14]:
DATE_COLS = ["date_mutation"]

In [15]:
INT_COLS = [
    "numero_disposition",
    "numero_volume", 
    "nombre_lots",
    "nombre_pieces_principales"
]

In [16]:
FLOAT_COLS = [
    "valeur_fonciere",
    "lot1_surface_carrez",
    "lot2_surface_carrez",
    "lot3_surface_carrez",
    "lot4_surface_carrez",
    "lot5_surface_carrez",
    "surface_reelle_bati",
    "surface_terrain",
    "longitude",
    "latitude"
]

In [17]:
STR_COLS = [
    "id_mutation",
    "nature_mutation",
    "adresse_numero",
    "adresse_suffixe",
    "adresse_nom_voie",
    "adresse_code_voie",
    "code_postal",
    "code_commune",
    "nom_commune",
    "code_departement",
    "ancien_code_commune",
    "id_parcelle",
    "ancien_id_parcelle",
    "lot1_numero", 
    "lot2_numero", 
    "lot3_numero",
    "lot4_numero",
    "lot5_numero",
    "code_type_local",
    "lot5_surface_carrez",
    "type_local",
    "code_nature_culture",	
    "nature_culture",
    "code_nature_culture_speciale",
    "nature_culture_speciale",
    "section_prefixe"
]

In [ ]:
dvf_silver = dvf_df.with_columns(
    pl.col(DATE_COLS).str.to_date("%Y-%m-%d"),
    pl.col(INT_COLS).cast(pl.Int64),
    pl.col(FLOAT_COLS)
        .str.replace_all(",", ".")
        .cast(pl.Float64),
)

In [19]:
dvf_silver.sample(5)

shape: (5, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ surface_t ┆ longitude ┆ latitude  ┆ section_ │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ errain    ┆ ---       ┆ ---       ┆ prefixe  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ f64       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2023-1354 ┆ 2023-09-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ 2.339769  ┆ 48.830995 ┆ 000AT    │
│ 546       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8292 ┆ 2020-12-1 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ 2.322154  ┆ 48.885807 ┆ 000CO    │
│ 83        ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-1662 ┆ 2022-12-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ 2.331786  ┆ 48.889521 ┆ 000AK    │
│ 934       ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1201 ┆ 2024-09-0 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ 2.296977  ┆ 48.881869 ┆ 000AM    │
│ 665       ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-5007 ┆ 2025-03-3 ┆ 1         ┆ Vente     ┆ … ┆ 1250.0    ┆ 2.322118  ┆ 48.855697 ┆ 000AL    │
│ 58        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
dvf_silver.shape

(395605, 41)

### 3. Valeurs uniques colonnes textuelles

In [14]:
text_cols = [
    "nature_mutation",
    "adresse_nom_voie",
    "code_postal",
    "nom_commune",
    "code_departement",
    "type_local"
    ]

In [15]:
# Occurences des observations pour certaines colonnes textuels
for i in text_cols:
    print(f"Fréquence des catégories pour la colonne: {i}")
    print(dvf_silver[i].value_counts(sort=True))
    print("-----------------------------------------------\n")

Fréquence des catégories pour la colonne: nature_mutation
shape: (6, 2)
┌─────────────────────────────────┬────────┐
│ nature_mutation                 ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Vente                           ┆ 388302 │
│ Vente en l'état futur d'achève… ┆ 3290   │
│ Echange                         ┆ 3127   │
│ Adjudication                    ┆ 837    │
│ Vente terrain à bâtir           ┆ 46     │
│ Expropriation                   ┆ 3      │
└─────────────────────────────────┴────────┘
-----------------------------------------------

Fréquence des catégories pour la colonne: adresse_nom_voie
shape: (3_872, 2)
┌───────────────────────┬───────┐
│ adresse_nom_voie      ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ RUE LECOURBE          ┆ 2531  │
│ RUE DE VAUGIRARD      ┆ 2260  │
│ RUE SAINT MAUR        ┆ 1845  │
│ RUE DU FBG ST ANTOINE ┆ 1767  │
│ BD VOLTAIRE           ┆ 1628  │
│ …                     ┆ …     │
│ RUE LEONTINE          ┆ 1     │
│ RUE CHEREAU           ┆ 1     │
│ IMP DU PETIT MODELE   ┆ 1     │
│ RUE DE CICE           ┆ 1     │
│ RUE LOUIS BOILLY      ┆ 1     │
└───────────────────────┴───────┘
-----------------------------------------------

Fréquence des catégories pour la colonne: code_postal
shape: (21, 2)
┌─────────────┬───────┐
│ code_postal ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ 75015       ┆ 41962 │
│ 75016       ┆ 41246 │
│ 75017       ┆ 30929 │
│ 75018       ┆ 30868 │
│ 75011       ┆ 30361 │
│ …           ┆ …     │
│ 75003       ┆ 7386  │
│ 75004       ┆ 5871  │
│ 75002       ┆ 4947  │
│ 75001       ┆ 3808  │
│ null        ┆ 1336  │
└─────────────┴───────┘
-----------------------------------------------

Fréquence des catégories pour la colonne: nom_commune
shape: (20, 2)
┌──────────────────────────┬───────┐
│ nom_commune              ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ Paris 15e Arrondissement ┆ 42074 │
│ Paris 16e Arrondissement ┆ 41303 │
│ Paris 17e Arrondissement ┆ 30952 │
│ Paris 18e Arrondissement ┆ 30870 │
│ Paris 11e Arrondissement ┆ 30362 │
│ …                        ┆ …     │
│ Paris 5e Arrondissement  ┆ 11717 │
│ Paris 3e Arrondissement  ┆ 7388  │
│ Paris 4e Arrondissement  ┆ 5873  │
│ Paris 2e Arrondissement  ┆ 4947  │
│ Paris 1er Arrondissement ┆ 3861  │
└──────────────────────────┴───────┘
-----------------------------------------------

Fréquence des catégories pour la colonne: code_departement
shape: (1, 2)
┌──────────────────┬────────┐
│ code_departement ┆ count  │
│ ---              ┆ ---    │
│ str              ┆ u32    │
╞══════════════════╪════════╡
│ 75               ┆ 395605 │
└──────────────────┴────────┘
-----------------------------------------------

Fréquence des catégories pour la colonne: type_local
shape: (5, 2)
┌─────────────────────────────────┬────────┐
│ type_local                      ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Appartement                     ┆ 186872 │
│ Dépendance                      ┆ 176240 │
│ Local industriel. commercial o… ┆ 27325  │
│ null                            ┆ 4207   │
│ Maison                          ┆ 961    │
└─────────────────────────────────┴────────┘
-----------------------------------------------

### 4. Traitement des données manquantes

In [16]:
dvf_silver.null_count()

shape: (1, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ surface_t ┆ longitude ┆ latitude ┆ section_p │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ errain    ┆ ---       ┆ ---      ┆ refixe    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ u32       ┆ u32      ┆ ---       │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆           ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 356808    ┆ 580       ┆ 580      ┆ 0         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [17]:
crit_cols = [
    "valeur_fonciere",
    "adresse_numero",
    "adresse_nom_voie",
    "code_postal",
    "type_local",
    "surface_reelle_bati",
    "nombre_pieces_principales"
    ]

- #### code_postal

In [66]:
# Utilisation de code commune (aucun null) pour déduire code postal
dvf_silver = dvf_silver.with_columns(
    pl.when(
        pl.col("code_postal").is_null()
        & pl.col("code_commune").is_not_null()
    )
    .then(
        pl.lit("750") + pl.col("code_commune").str.slice(-2)
    )
    .otherwise(pl.col("code_postal"))
    .alias("code_postal")
)

In [19]:
dvf_silver.shape

(395605, 41)

- #### adresse_nom_voie

In [67]:
# Adresse manquantes se présentant comme des doublons ou plus
adrs_srch = dvf_silver.group_by(["id_mutation","code_postal","valeur_fonciere"]).agg(pl.col("adresse_nom_voie").unique())
sus_adrs = adrs_srch.filter(pl.col("adresse_nom_voie").list.contains(None) &
                 (pl.col("adresse_nom_voie").list.len() >= 2))

In [68]:
# id de mutation des lignes se présentant comme des doublons
ids = sus_adrs.get_column("id_mutation").unique().to_list()

In [69]:
# Ajout d'une colonne flag pour les lignes suspectes
dvf_silver = dvf_silver.with_columns(
    pl.when(pl.col("id_mutation").is_in(ids)
            & pl.col("adresse_nom_voie").is_null()
            )
    .then(True)
    .otherwise(False)
    .alias("suspect_rows")
)

In [70]:
# Drop des lignes suspectes
dvf_silver = dvf_silver.filter(~pl.col("suspect_rows"))

In [24]:
dvf_silver.shape

(395463, 42)

- #### adresse_numero

In [71]:
# Adresse manquantes se présentant comme des doublons ou plus
adrs_srch = dvf_silver.group_by(["id_mutation","valeur_fonciere","adresse_nom_voie"]).agg(pl.col("adresse_numero").unique())
sus_adrs = adrs_srch.filter(pl.col("adresse_numero").list.contains(None)
                            & (pl.col("adresse_numero").list.len() >= 2))

In [72]:
# id de mutation des lignes se présentant comme des doublons
ids = sus_adrs.get_column("id_mutation").unique().to_list()

In [73]:
# Ajout d'une colonne flag pour les lignes suspectes
dvf_silver = dvf_silver.with_columns(
    pl.when(pl.col("id_mutation").is_in(ids)
            & pl.col("adresse_numero").is_null()
            )
    .then(True)
    .otherwise(False)
    .alias("suspect_rows")
)

In [74]:
# Drop des lignes suspectes
dvf_silver = dvf_silver.filter(~pl.col("suspect_rows"))

In [29]:
dvf_silver.shape

(395456, 42)

In [ ]:
rows_to_impute = (
    dvf_silver
    .filter((
            pl.col("adresse_numero").is_null()
            | pl.col("adresse_nom_voie").is_null()) 
            & pl.col("longitude").is_not_null() 
            & pl.col("latitude").is_not_null()
            )
    .select(["id_mutation", "longitude", "latitude", "code_postal", "code_commune"])
)

In [31]:
BASE_URL = "https://data.geopf.fr/geocodage/reverse"

def reverse_geocode_fr(lon, lat, postcode=None, citycode=None):
    params = {
        "index": "address",
        "lon": lon,
        "lat": lat,
        "limit": 1,
    }

    if postcode is not None:
        params["postcode"] = str(postcode)
    if citycode is not None:
        params["citycode"] = str(citycode)

    r = requests.get(BASE_URL, params=params, timeout=10)
    r.raise_for_status()
    data = r.json()

    features = data.get("features", [])
    if not features:
        return None

    props = features[0]["properties"]

    return {
        "full_address_geocoded": props.get("label"),
        "street_geocoded": props.get("street"),
        "housenumber_geocoded": props.get("housenumber"),
        "postcode_geocoded": props.get("postcode"),
        "city_geocoded": props.get("city"),
        "citycode_geocoded": props.get("citycode"),
        "score_geocoded": props.get("score"),
    }

In [32]:
results = []

for row in rows_to_impute.iter_rows(named=True):
    try:
        geo = reverse_geocode_fr(
            lon=row["longitude"],
            lat=row["latitude"],
            postcode=row["code_postal"],
        )

        if geo is None:
            results.append({
                "id_mutation": row["id_mutation"],
                "street_geocoded": None,
                "postcode_geocoded": None,
                "citycode_geocoded": None,
                "score_geocoded": None,
                "address_inferred_from_coords": False,
                "lon": row["longitude"],
                "lat": row["latitude"]
            })
            continue

        results.append({
            "id_mutation": row["id_mutation"],
            **geo,
            "address_inferred_from_coords": True,
            "lon": row["longitude"],
            "lat": row["latitude"]
        })

        time.sleep(0.05)  # petite pause prudente
    except Exception:
        results.append({
            "id_mutation": row["id_mutation"],
            "street_geocoded": None,
            "postcode_geocoded": None,
            "citycode_geocoded": None,
            "score_geocoded": None,
            "address_inferred_from_coords": False,
            "lon": row["longitude"],
            "lat": row["latitude"]
        })

In [75]:
geo_df = pl.DataFrame(results)

In [34]:
geo_df.head()

shape: (5, 11)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ id_mutatio ┆ full_addr ┆ street_ge ┆ housenumb ┆ … ┆ score_geo ┆ address_i ┆ lon      ┆ lat      │
│ n          ┆ ess_geoco ┆ ocoded    ┆ er_geocod ┆   ┆ coded     ┆ nferred_f ┆ ---      ┆ ---      │
│ ---        ┆ ded       ┆ ---       ┆ ed        ┆   ┆ ---       ┆ rom_coord ┆ f64      ┆ f64      │
│ str        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64       ┆ s         ┆          ┆          │
│            ┆ str       ┆           ┆ str       ┆   ┆           ┆ ---       ┆          ┆          │
│            ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆          ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ 2020-81516 ┆ 140a Rue  ┆ Rue de    ┆ 140a      ┆ … ┆ 0.9983    ┆ true      ┆ 2.343056 ┆ 48.86059 │
│ 5          ┆ de Rivoli ┆ Rivoli    ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 75001     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 2020-81516 ┆ 140a Rue  ┆ Rue de    ┆ 140a      ┆ … ┆ 0.9983    ┆ true      ┆ 2.343056 ┆ 48.86059 │
│ 5          ┆ de Rivoli ┆ Rivoli    ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 75001     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 2020-81516 ┆ 140a Rue  ┆ Rue de    ┆ 140a      ┆ … ┆ 0.9983    ┆ true      ┆ 2.343056 ┆ 48.86059 │
│ 5          ┆ de Rivoli ┆ Rivoli    ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 75001     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 2020-81516 ┆ 140a Rue  ┆ Rue de    ┆ 140a      ┆ … ┆ 0.9983    ┆ true      ┆ 2.343056 ┆ 48.86059 │
│ 5          ┆ de Rivoli ┆ Rivoli    ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 75001     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 2020-81512 ┆ 140a Rue  ┆ Rue de    ┆ 140a      ┆ … ┆ 0.9983    ┆ true      ┆ 2.343056 ┆ 48.86059 │
│ 6          ┆ de Rivoli ┆ Rivoli    ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 75001     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

In [35]:
geo_df.filter(pl.col("housenumber_geocoded").str.contains("[a-zA-Z]")).sample(5)

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ id_mutati ┆ full_addr ┆ street_ge ┆ housenumb ┆ … ┆ score_geo ┆ address_i ┆ lon      ┆ lat       │
│ on        ┆ ess_geoco ┆ ocoded    ┆ er_geocod ┆   ┆ coded     ┆ nferred_f ┆ ---      ┆ ---       │
│ ---       ┆ ded       ┆ ---       ┆ ed        ┆   ┆ ---       ┆ rom_coord ┆ f64      ┆ f64       │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64       ┆ s         ┆          ┆           │
│           ┆ str       ┆           ┆ str       ┆   ┆           ┆ ---       ┆          ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 2020-8226 ┆ 1p Rue    ┆ Rue       ┆ 1p        ┆ … ┆ 0.9989    ┆ true      ┆ 2.373495 ┆ 48.832038 │
│ 49        ┆ Alphonse  ┆ Alphonse  ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Boudard   ┆ Boudard   ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ 75013 …   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2021-1702 ┆ 163p1     ┆ Avenue de ┆ 163p1     ┆ … ┆ 0.9977    ┆ true      ┆ 2.373369 ┆ 48.833202 │
│ 892       ┆ Avenue de ┆ France    ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ France    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ 75013 P…  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2022-1674 ┆ 46p Rue   ┆ Rue       ┆ 46p       ┆ … ┆ 0.9987    ┆ true      ┆ 2.305577 ┆ 48.842798 │
│ 504       ┆ Blomet    ┆ Blomet    ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ 75015     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2023-1352 ┆ 31a Rue   ┆ Rue       ┆ 31a       ┆ … ┆ 0.9947    ┆ true      ┆ 2.354633 ┆ 48.829151 │
│ 006       ┆ Bobillot  ┆ Bobillot  ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ 75013     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2024-1198 ┆ 33p Rue   ┆ Rue Piat  ┆ 33p       ┆ … ┆ 0.9981    ┆ true      ┆ 2.383828 ┆ 48.872324 │
│ 208       ┆ Piat      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ 75020     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Paris     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [76]:
geo_df = geo_df.with_columns(
    pl.when(pl.col("housenumber_geocoded").str.contains("[a-zA-Z]"))
    .then(
        pl.col("housenumber_geocoded").str.extract(r"^(\d+)", group_index=1)
    )
    .otherwise(pl.col("housenumber_geocoded"))
    .alias("adresse_numero_clean")
)

In [77]:
ABBREVIATIONS = {
    "BOULEVARD": "BD",
    "PASSAGE": "PAS",
    "AVENUE": "AV",
    "IMPASSE": "IMP",
    "PLACE": "PL",
    "ROUTE": "RTE",
    "ALLEE": "ALL",
    "SQUARE": "SQ",
    "VILLA": "VLA",
    "FAUBOURG": "FG",
    "CHEMIN": "CHE",
}

In [38]:
def normalize_voie(s: str) -> str:
    if s is None:
        return None

    # Uppercase
    s = s.upper()

    # Suppression des accents
    s = "".join(
        c for c in unicodedata.normalize("NFD", s)
        if not unicodedata.combining(c)
    )

    # Apostrophes / tirets / séparateurs -> espace
    s = re.sub(r"['’`´\-_/.,;:()]", " ", s)

    # Abréviations
    for mot, abbr in ABBREVIATIONS.items():
        s = re.sub(rf"\b{mot}\b", abbr, s)

    # Ne garder que lettres, chiffres et espaces
    s = re.sub(r"[^A-Z0-9 ]", " ", s)

    # Normalisation des espaces
    s = re.sub(r"\s+", " ", s).strip()

    return s

In [39]:
geo_df.shape

(1242, 12)

In [78]:
col_to_keep = [
    "id_mutation",
    "postcode_geocoded",
    "score_geocoded",
    "address_inferred_from_coords",
    "lon",
    "lat",
    "adresse_numero_clean",
    "street_geocoded"
    ]

In [79]:
geo_df = geo_df.unique(subset=["id_mutation","lon","lat"], maintain_order=True)

In [80]:
dvf_silver = dvf_silver.join(geo_df[col_to_keep],
                                   left_on=["id_mutation","longitude","latitude"],
                                   right_on=["id_mutation","lon","lat"],
                                   how="left",
                                   validate="m:1"
                                   )

In [81]:
dvf_silver = dvf_silver.with_columns(
    pl.when(pl.col("address_inferred_from_coords").is_null())
    .then(False)
    .otherwise(True)
    .alias("address_inferred_from_coords")
    ,
    pl.when(pl.col("address_inferred_from_coords") & 
            (pl.col("score_geocoded") > 0.9))
    .then(pl.col("adresse_numero_clean"))
    .otherwise(pl.col("adresse_numero"))
    .alias("adresse_numero")
    ,
    pl.when(pl.col("address_inferred_from_coords") &
            (pl.col("score_geocoded") > 0.9))
    .then(pl.col("street_geocoded"))
    .otherwise(pl.col("adresse_nom_voie"))
    .alias("adresse_nom_voie")
)

In [82]:
dvf_silver = dvf_silver.with_columns(
    pl.col("adresse_nom_voie")
    .map_elements(normalize_voie, return_dtype=pl.String)
    .alias("adresse_nom_voie")
)

In [45]:
dvf_silver.null_count()

shape: (1, 47)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ score_geo ┆ address_i ┆ adresse_n ┆ street_g │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ coded     ┆ nferred_f ┆ umero_cle ┆ eocoded  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ rom_coord ┆ an        ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ s         ┆ ---       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ u32       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 394208    ┆ 0         ┆ 394232    ┆ 394232   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
geo_df.null_count()

shape: (1, 12)
┌─────────────┬─────────────┬─────────────┬─────────────┬───┬─────────────┬─────┬─────┬────────────┐
│ id_mutation ┆ full_addres ┆ street_geoc ┆ housenumber ┆ … ┆ address_inf ┆ lon ┆ lat ┆ adresse_nu │
│ ---         ┆ s_geocoded  ┆ oded        ┆ _geocoded   ┆   ┆ erred_from_ ┆ --- ┆ --- ┆ mero_clean │
│ u32         ┆ ---         ┆ ---         ┆ ---         ┆   ┆ coords      ┆ u32 ┆ u32 ┆ ---        │
│             ┆ u32         ┆ u32         ┆ u32         ┆   ┆ ---         ┆     ┆     ┆ u32        │
│             ┆             ┆             ┆             ┆   ┆ u32         ┆     ┆     ┆            │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══╪═════════════╪═════╪═════╪════════════╡
│ 0           ┆ 0           ┆ 11          ┆ 11          ┆ … ┆ 0           ┆ 0   ┆ 0   ┆ 11         │
└─────────────┴─────────────┴─────────────┴─────────────┴───┴─────────────┴─────┴─────┴────────────┘

- #### valeur_fonciere, surface_relle_bati, nombre_pieces_principales

In [49]:
crit_cols

['valeur_fonciere',
 'adresse_numero',
 'adresse_nom_voie',
 'code_postal',
 'type_local',
 'surface_reelle_bati',
 'nombre_pieces_principales']

In [50]:
dvf_silver.null_count()

shape: (1, 47)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ score_geo ┆ address_i ┆ adresse_n ┆ street_g │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ coded     ┆ nferred_f ┆ umero_cle ┆ eocoded  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ rom_coord ┆ an        ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ s         ┆ ---       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ u32       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 394208    ┆ 0         ┆ 394232    ┆ 394232   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [84]:
dvf_silver = dvf_silver.with_columns(
    pl.col("valeur_fonciere").is_null().alias("is_valeur_fonciere_missing"),
    pl.col("surface_reelle_bati").is_null().alias("is_surface_missing"),
    pl.col("nombre_pieces_principales").is_null().alias("is_nombre_pieces_missing")
)

- #### type_local

In [85]:
dvf_silver = dvf_silver.with_columns(
    pl.when(pl.col("type_local").is_null())
    .then(pl.lit("Indisponible"))
    .otherwise(pl.col("type_local"))
    .alias("type_local")
)

In [53]:
dvf_silver

shape: (395_456, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ street_ge ┆ vf_missin ┆ sr_missin ┆ np_missi │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ ocoded    ┆ g_flag    ┆ g_flag    ┆ ng_flag  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ str       ┆ bool      ┆ bool      ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-8151 ┆ 2020-10-0 ┆ 1         ┆ Vente     ┆ … ┆ Rue de    ┆ false     ┆ true      ┆ true     │
│ 65        ┆ 8         ┆           ┆           ┆   ┆ Rivoli    ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ true      ┆ false    │
│ 07        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ false     ┆ false    │
│ 08        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ true      ┆ false    │
│ 09        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ true      ┆ false    │
│ 09        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-1213 ┆ 2024-04-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ false     ┆ false    │
│ 647       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1213 ┆ 2024-04-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ false     ┆ false    │
│ 647       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1213 ┆ 2024-04-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ true      ┆ false    │
│ 647       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1213 ┆ 2024-04-2 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ true      ┆ false    │
│ 647       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1213 ┆ 2024-05-1 ┆ 1         ┆ Vente     ┆ … ┆ null      ┆ false     ┆ false     ┆ false    │
│ 648       ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 5. Sélection des colonnes

In [86]:
col_to_keep = [
    "id_mutation",
    "date_mutation",
    "numero_disposition",
    "nature_mutation",
    "valeur_fonciere",
    "adresse_numero",
    "adresse_nom_voie",
    "code_postal",
    "code_commune",
    "nom_commune",
    "code_departement",
    "nombre_lots",
    "type_local",
    "surface_reelle_bati",
    "nombre_pieces_principales",
    "address_inferred_from_coords",
    "is_valeur_fonciere_missing",
    "is_surface_missing",
    "is_nombre_pieces_missing"
]

In [87]:
dvf_silver = dvf_silver[col_to_keep]
dvf_silver.sample(5)

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ address_i ┆ is_valeur ┆ is_surfac ┆ is_nombr │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ nferred_f ┆ _fonciere ┆ e_missing ┆ e_pieces │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ rom_coord ┆ _missing  ┆ ---       ┆ _missing │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ s         ┆ ---       ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ bool      ┆           ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-1693 ┆ 2021-09-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ true      ┆ false    │
│ 596       ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8331 ┆ 2020-11-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 92        ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-5015 ┆ 2025-04-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ true      ┆ false    │
│ 00        ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8206 ┆ 2020-10-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 92        ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-1201 ┆ 2024-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 685       ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [99]:
dvf_silver.null_count()

shape: (1, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ address_i ┆ is_valeur ┆ is_surfac ┆ is_nombr │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ nferred_f ┆ _fonciere ┆ e_missing ┆ e_pieces │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ rom_coord ┆ _missing  ┆ ---       ┆ _missing │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ s         ┆ ---       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ u32       ┆           ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 6. Lignes dupliquées

In [88]:
dvf_silver = dvf_silver.unique(maintain_order=True)

In [89]:
dvf_silver.shape

(205847, 19)

### 7. Valeurs invalides

In [90]:
dvf_silver.select(pl.col(pl.Int64, pl.Float64)).describe()

shape: (9, 6)
┌────────────┬─────────────────┬─────────────────┬─────────────┬─────────────────┬─────────────────┐
│ statistic  ┆ numero_disposit ┆ valeur_fonciere ┆ nombre_lots ┆ surface_reelle_ ┆ nombre_pieces_p │
│ ---        ┆ ion             ┆ ---             ┆ ---         ┆ bati            ┆ rincipales      │
│ str        ┆ ---             ┆ f64             ┆ f64         ┆ ---             ┆ ---             │
│            ┆ f64             ┆                 ┆             ┆ f64             ┆ f64             │
╞════════════╪═════════════════╪═════════════════╪═════════════╪═════════════════╪═════════════════╡
│ count      ┆ 205847.0        ┆ 205123.0        ┆ 205847.0    ┆ 122535.0        ┆ 204417.0        │
│ null_count ┆ 0.0             ┆ 724.0           ┆ 0.0         ┆ 83312.0         ┆ 1430.0          │
│ mean       ┆ 1.009094        ┆ 1.8141e6        ┆ 1.540348    ┆ 69.507243       ┆ 1.275633        │
│ std        ┆ 0.106505        ┆ 1.0618e7        ┆ 1.324535    ┆ 252.427659      ┆ 1.550966        │
│ min        ┆ 1.0             ┆ 0.15            ┆ 0.0         ┆ 1.0             ┆ 0.0             │
│ 25%        ┆ 1.0             ┆ 242857.0        ┆ 1.0         ┆ 27.0            ┆ 0.0             │
│ 50%        ┆ 1.0             ┆ 455760.0        ┆ 1.0         ┆ 44.0            ┆ 1.0             │
│ 75%        ┆ 1.0             ┆ 865000.0        ┆ 2.0         ┆ 71.0            ┆ 2.0             │
│ max        ┆ 9.0             ┆ 1.0034e9        ┆ 236.0       ┆ 28109.0         ┆ 32.0            │
└────────────┴─────────────────┴─────────────────┴─────────────┴─────────────────┴─────────────────┘

In [103]:
dvf_silver = dvf_silver.with_columns([
    pl.when((~pl.col("is_surface_missing")) 
            & (pl.col("surface_reelle_bati") <= 5)
    )
    .then(True)
    .otherwise(False)
    .alias("is_surface_tres_faible"),

    pl.when((~pl.col("is_valeur_fonciere_missing"))
            & (pl.col("valeur_fonciere") < 10_000)
    )
    .then(True)
    .otherwise(False)
    .alias("is_valeur_fonciere_tres_basse"),

    (
        (pl.col("type_local") == "Appartement") &
        (pl.col("nombre_lots") == 0)
    ).alias("is_appartement_sans_lot")])

In [107]:
dvf_silver = dvf_silver.with_columns([(
        (pl.col("is_surface_tres_faible")) |
        (pl.col("is_valeur_fonciere_tres_basse")) |
        (
            (pl.col("type_local") == "Appartement") &
            (pl.col("nombre_lots") == 0)
        )
    ).alias("is_transaction_atypique_agent")
])

In [108]:
dvf_silver.filter(pl.col("is_transaction_atypique_agent"))

shape: (10_976, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ is_surfac ┆ is_valeur ┆ is_appart ┆ is_trans │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ e_tres_fa ┆ _fonciere ┆ ement_san ┆ action_a │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ible      ┆ _tres_bas ┆ s_lot     ┆ typique_ │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ ---       ┆ se        ┆ ---       ┆ agent    │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ ---       ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 19        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 31        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 31        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 31        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 33        ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2021-1708 ┆ 2021-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ true      ┆ true     │
│ 383       ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1708 ┆ 2021-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ true      ┆ true     │
│ 383       ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1708 ┆ 2021-09-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 429       ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1708 ┆ 2021-09-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 590       ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1708 ┆ 2021-09-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ true      ┆ false     ┆ true     │
│ 602       ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

***


# BPE bronze cleaning

### 1. Import

In [21]:
bpe_df = pl.read_csv(BRONZE_DIR / "DS_BPE_2024_data.csv",
                     separator=";",
                     infer_schema_length=0
                     )

In [4]:
bpe_df.shape

(2300480, 8)

In [5]:
bpe_df.head()

shape: (5, 8)
┌─────┬────────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬───────────┐
│ GEO ┆ GEO_OBJECT ┆ FACILITY_DO ┆ FACILITY_SD ┆ FACILITY_TY ┆ BPE_MEASUR ┆ TIME_PERIO ┆ OBS_VALUE │
│ --- ┆ ---        ┆ M           ┆ OM          ┆ PE          ┆ E          ┆ D          ┆ ---       │
│ str ┆ str        ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ str       │
│     ┆            ┆ str         ┆ str         ┆ str         ┆ str        ┆ str        ┆           │
╞═════╪════════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪═══════════╡
│ 67  ┆ DEP        ┆ F           ┆ F1          ┆ F105        ┆ FACILITIES ┆ 2024       ┆ 3         │
│ 86  ┆ DEP        ┆ D           ┆ D6          ┆ D606        ┆ FACILITIES ┆ 2024       ┆ 3         │
│ 26  ┆ DEP        ┆ D           ┆ D6          ┆ D607        ┆ FACILITIES ┆ 2024       ┆ 4         │
│ 73  ┆ DEP        ┆ F           ┆ F1          ┆ F107        ┆ FACILITIES ┆ 2024       ┆ 33        │
│ 90  ┆ DEP        ┆ F           ┆ F1          ┆ F101        ┆ FACILITIES ┆ 2024       ┆ 5         │
└─────┴────────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴───────────┘

### 2. Typage des colonnes

In [22]:
DATE_COLS = ["TIME_PERIOD"]

In [23]:
INT_COLS = ["OBS_VALUE"]

In [6]:
STR_COLS = [
    "GEO",
    "GEO_OBJECT",
    "FACILITY_DOM",
    "FACILITY_SDOM",
    "FACILITY_TYPE",
    "BPE_MEASURE"
]

In [24]:
bpe_silver = bpe_df.with_columns(
    pl.col(DATE_COLS).str.to_date("%Y", strict=True).dt.year().cast(pl.Int64).alias("TIME_PERIOD"),
    pl.col(INT_COLS).cast(pl.Int64, strict=True)
)

In [24]:
bpe_silver.sample(5)

shape: (5, 8)
┌───────┬────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ GEO   ┆ GEO_OBJECT ┆ FACILITY_DO ┆ FACILITY_S ┆ FACILITY_T ┆ BPE_MEASUR ┆ TIME_PERIO ┆ OBS_VALUE │
│ ---   ┆ ---        ┆ M           ┆ DOM        ┆ YPE        ┆ E          ┆ D          ┆ ---       │
│ str   ┆ str        ┆ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ i64       │
│       ┆            ┆ str         ┆ str        ┆ str        ┆ str        ┆ i64        ┆           │
╞═══════╪════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 58033 ┆ COM        ┆ _T          ┆ _T         ┆ _T         ┆ FACILITIES ┆ 2024       ┆ 7         │
│ 49328 ┆ COM        ┆ B           ┆ B3         ┆ B326       ┆ FACILITIES ┆ 2024       ┆ 15        │
│ 42285 ┆ COM        ┆ F           ┆ F1         ┆ F114       ┆ FACILITIES ┆ 2024       ┆ 1         │
│ 34032 ┆ BV2022     ┆ B           ┆ B2         ┆ B204       ┆ FACILITIES ┆ 2024       ┆ 55        │
│ 31451 ┆ COM        ┆ D           ┆ D2         ┆ D274       ┆ FACILITIES ┆ 2024       ┆ 1         │
└───────┴────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

### 3. Slicing des données

In [25]:
code_arr = ["75101",
            "75102",
            "75103",
            "75104",
            "75105",
            "75106",
            "75107",
            "75108",
            "75109",
            "75110",
            "75111",
            "75112",
            "75113",
            "75114",
            "75115",
            "75116",
            "75117",
            "75118",
            "75119",
            "75120"]

In [26]:
bpe_silver = bpe_silver.filter(pl.col("GEO").is_in(code_arr))
bpe_silver.sample(5)

shape: (5, 8)
┌───────┬────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ GEO   ┆ GEO_OBJECT ┆ FACILITY_DO ┆ FACILITY_S ┆ FACILITY_T ┆ BPE_MEASUR ┆ TIME_PERIO ┆ OBS_VALUE │
│ ---   ┆ ---        ┆ M           ┆ DOM        ┆ YPE        ┆ E          ┆ D          ┆ ---       │
│ str   ┆ str        ┆ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ i64       │
│       ┆            ┆ str         ┆ str        ┆ str        ┆ str        ┆ i64        ┆           │
╞═══════╪════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 75107 ┆ ARM        ┆ B           ┆ _T         ┆ _T         ┆ FACILITIES ┆ 2024       ┆ 1043      │
│ 75111 ┆ ARM        ┆ F           ┆ F1         ┆ F101       ┆ FACILITIES ┆ 2024       ┆ 5         │
│ 75104 ┆ ARM        ┆ A           ┆ A2         ┆ A203       ┆ FACILITIES ┆ 2024       ┆ 21        │
│ 75113 ┆ ARM        ┆ D           ┆ D2         ┆ D262       ┆ FACILITIES ┆ 2024       ┆ 8         │
│ 75105 ┆ ARM        ┆ D           ┆ _T         ┆ _T         ┆ FACILITIES ┆ 2024       ┆ 1050      │
└───────┴────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

In [13]:
bpe_silver.shape

(3773, 8)

### 4. Valeurs manquantes

In [12]:
bpe_silver.null_count()

shape: (1, 8)
┌─────┬────────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬───────────┐
│ GEO ┆ GEO_OBJECT ┆ FACILITY_DO ┆ FACILITY_SD ┆ FACILITY_TY ┆ BPE_MEASUR ┆ TIME_PERIO ┆ OBS_VALUE │
│ --- ┆ ---        ┆ M           ┆ OM          ┆ PE          ┆ E          ┆ D          ┆ ---       │
│ u32 ┆ u32        ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ u32       │
│     ┆            ┆ u32         ┆ u32         ┆ u32         ┆ u32        ┆ u32        ┆           │
╞═════╪════════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪═══════════╡
│ 0   ┆ 0          ┆ 0           ┆ 0           ┆ 0           ┆ 0          ┆ 0          ┆ 0         │
└─────┴────────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴───────────┘

Aucune valeur nulle identifiée

### 5. Lignes dupliquées

In [14]:
bpe_silver.unique().shape

(3773, 8)

Aucun doublon identifié

### 6. Ajustement des colonnes

In [27]:
df_codes_dom = pl.read_csv(BRONZE_DIR / "codes_FACILITY_DOM_BPE.csv",
                           separator=";",
                           infer_schema_length=0,
                           encoding="windows-1252"
                           )
df_codes_dom = df_codes_dom.rename({"libelle français":"classification_n1"})
df_codes_dom

shape: (8, 2)
┌──────┬────────────────────────────────┐
│ code ┆ classification_n1              │
│ ---  ┆ ---                            │
│ str  ┆ str                            │
╞══════╪════════════════════════════════╡
│ _T   ┆ Total                          │
│ A    ┆ Services pour les particuliers │
│ B    ┆ Commerces                      │
│ C    ┆ Enseignement                   │
│ D    ┆ Santé et action sociale        │
│ E    ┆ Transports et déplacements     │
│ F    ┆ Sports, loisirs et culture     │
│ G    ┆ Tourisme                       │
└──────┴────────────────────────────────┘

In [28]:
df_codes_sdom = pl.read_csv(BRONZE_DIR / "codes_FACILITY_SDOM_BPE.csv",
                            separator=";",
                            infer_schema_length=0,
                            encoding="windows-1252"
                            )
df_codes_sdom = df_codes_sdom.rename({"libelle français":"classification_n2"})
df_codes_sdom.sample(5)

shape: (5, 2)
┌──────┬─────────────────────────────────┐
│ code ┆ classification_n2               │
│ ---  ┆ ---                             │
│ str  ┆ str                             │
╞══════╪═════════════════════════════════╡
│ D1   ┆ Etablissements et services de … │
│ A3   ┆ Services automobiles            │
│ C2   ┆ Enseignement du second degré -… │
│ A1   ┆ Services publics                │
│ D6   ┆ Action sociale pour handicapés  │
└──────┴─────────────────────────────────┘

In [29]:
df_codes_type = pl.read_csv(BRONZE_DIR / "codes_FACILITY_TYPE_BPE.csv",
                            separator=";",
                            infer_schema_length=0,
                            encoding="windows-1252"
                            )
df_codes_type = df_codes_type.rename({"libelle français":"classification_n3"})
df_codes_type.sample(5)

shape: (5, 2)
┌──────┬─────────────────────────────────┐
│ code ┆ classification_n3               │
│ ---  ┆ ---                             │
│ str  ┆ str                             │
╞══════╪═════════════════════════════════╡
│ D270 ┆ Spécialiste en ophtalmologie    │
│ F110 ┆ Sports de glace                 │
│ B311 ┆ Horlogerie-bijouterie           │
│ D115 ┆ Services de santé maternelle e… │
│ C410 ┆ école de formation aux profess… │
└──────┴─────────────────────────────────┘

In [30]:
bpe_silver = bpe_silver.join(df_codes_dom,
                        left_on=["FACILITY_DOM"],
                        right_on=["code"],
                        how="left",
                        validate="m:1"
                        )

In [31]:
bpe_silver = bpe_silver.join(df_codes_sdom,
                        left_on=["FACILITY_SDOM"],
                        right_on=["code"],
                        how="left",
                        validate="m:1"
                        )

In [32]:
bpe_silver = bpe_silver.join(df_codes_type,
                        left_on=["FACILITY_TYPE"],
                        right_on=["code"],
                        how="left",
                        validate="m:1"
                        )

In [33]:
bpe_silver = bpe_silver.with_columns((pl.lit("750") + pl.col("GEO")
                                     .str.slice(-2))
                                     .alias("code_postal")
                                     )
bpe_silver.sample(5)

shape: (5, 12)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GEO   ┆ GEO_OBJECT ┆ FACILITY_D ┆ FACILITY_S ┆ … ┆ classific ┆ classific ┆ classific ┆ code_post │
│ ---   ┆ ---        ┆ OM         ┆ DOM        ┆   ┆ ation_n1  ┆ ation_n2  ┆ ation_n3  ┆ al        │
│ str   ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆ str        ┆ str        ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 75108 ┆ ARM        ┆ A          ┆ A5         ┆ … ┆ Services  ┆ Autres    ┆ Vétérinai ┆ 75008     │
│       ┆            ┆            ┆            ┆   ┆ pour les  ┆ services  ┆ re        ┆           │
│       ┆            ┆            ┆            ┆   ┆ particuli ┆           ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ ers       ┆           ┆           ┆           │
│ 75105 ┆ ARM        ┆ B          ┆ B3         ┆ … ┆ Commerces ┆ Commerces ┆ Commerce  ┆ 75005     │
│       ┆            ┆            ┆            ┆   ┆           ┆ spécialis ┆ de jeux   ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ és        ┆ et jouets ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ non-alim… ┆           ┆           │
│ 75101 ┆ ARM        ┆ D          ┆ D2         ┆ … ┆ Santé et  ┆ Fonctions ┆ Psycholog ┆ 75001     │
│       ┆            ┆            ┆            ┆   ┆ action    ┆ médicales ┆ ue        ┆           │
│       ┆            ┆            ┆            ┆   ┆ sociale   ┆ et        ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ paraméd…  ┆           ┆           │
│ 75102 ┆ ARM        ┆ D          ┆ D2         ┆ … ┆ Santé et  ┆ Fonctions ┆ Médecin   ┆ 75002     │
│       ┆            ┆            ┆            ┆   ┆ action    ┆ médicales ┆ généralis ┆           │
│       ┆            ┆            ┆            ┆   ┆ sociale   ┆ et        ┆ te        ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ paraméd…  ┆           ┆           │
│ 75115 ┆ ARM        ┆ A          ┆ A3         ┆ … ┆ Services  ┆ Services  ┆ Total     ┆ 75015     │
│       ┆            ┆            ┆            ┆   ┆ pour les  ┆ automobil ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ particuli ┆ es        ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ ers       ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [34]:
bpe_silver = bpe_silver.rename({"TIME_PERIOD":"annee", "OBS_VALUE":"nombre_equipements"})

In [60]:
test = bpe_silver["BPE_MEASURE"].unique().to_list()
test

['FACILITIES']

In [35]:
col_to_keep = ["annee",
               "code_postal",
               "classification_n1",
               "classification_n2",
               "classification_n3",
               "nombre_equipements"
               ]

In [36]:
bpe_silver = bpe_silver[col_to_keep]

In [63]:
bpe_silver.sample(5)

shape: (5, 6)
┌───────┬─────────────┬───────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ annee ┆ code_postal ┆ classification_n1 ┆ classification_n ┆ classification_n ┆ nombre_equipemen │
│ ---   ┆ ---         ┆ ---               ┆ 2                ┆ 3                ┆ ts               │
│ i64   ┆ str         ┆ str               ┆ ---              ┆ ---              ┆ ---              │
│       ┆             ┆                   ┆ str              ┆ str              ┆ i64              │
╞═══════╪═════════════╪═══════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ 2024  ┆ 75008       ┆ Tourisme          ┆ Tourisme         ┆ Hôtel            ┆ 153              │
│ 2024  ┆ 75012       ┆ Santé et action   ┆ Fonctions        ┆ Médecin          ┆ 125              │
│       ┆             ┆ sociale           ┆ médicales et     ┆ généraliste      ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75014       ┆ Services pour les ┆ Artisanat du     ┆ Plâtrier peintre ┆ 165              │
│       ┆             ┆ particuliers      ┆ bâtiment         ┆                  ┆                  │
│ 2024  ┆ 75013       ┆ Services pour les ┆ Services publics ┆ Total            ┆ 9                │
│       ┆             ┆ particuliers      ┆                  ┆                  ┆                  │
│ 2024  ┆ 75010       ┆ Santé et action   ┆ Action sociale   ┆ Relais petite    ┆ 2                │
│       ┆             ┆ sociale           ┆ pour enfants en… ┆ enfance          ┆                  │
└───────┴─────────────┴───────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [37]:
bpe_silver.shape

(3773, 6)

In [38]:
bpe_silver.head()

shape: (5, 6)
┌───────┬─────────────┬───────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ annee ┆ code_postal ┆ classification_n1 ┆ classification_n ┆ classification_n ┆ nombre_equipemen │
│ ---   ┆ ---         ┆ ---               ┆ 2                ┆ 3                ┆ ts               │
│ i64   ┆ str         ┆ str               ┆ ---              ┆ ---              ┆ ---              │
│       ┆             ┆                   ┆ str              ┆ str              ┆ i64              │
╞═══════╪═════════════╪═══════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ 2024  ┆ 75004       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 26               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ cardiologie      ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75004       ┆ Commerces         ┆ Commerces        ┆ Station de       ┆ 13               │
│       ┆             ┆                   ┆ spécialisés      ┆ recharge de      ┆                  │
│       ┆             ┆                   ┆ non-alim…        ┆ véhicul…         ┆                  │
│ 2024  ┆ 75003       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 4                │
│       ┆             ┆ sociale           ┆ médicales et     ┆ pédiatrie        ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75014       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 38               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ oncologie, anat… ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75010       ┆ Commerces         ┆ Commerces        ┆ Supérette        ┆ 26               │
│       ┆             ┆                   ┆ alimentaires     ┆                  ┆                  │
└───────┴─────────────┴───────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [6]:
test = bpe_df.filter(pl.Series(bpe_df.select("GEO")).str.contains("^751.*"))
res = test.select("GEO").to_series().unique().to_list()
len(res)

31

In [ ]:
unique_geo = pl.Series(bpe_df.select("GEO"))
unique_geo.str.contains("751")